### ISSUE TITLE
Bump psr/log version

### ISSUE THREAD

**Issue by VGirol** [webeweb/gouv-api-library#1]
Is it possible to upgrade the psr/log package to version 3.0 ?

**Comment by webeweb** [comment]
Hi

Maybe, I take a look the next week.

Best regards

**Comment by webeweb** [comment]
Hi,

The release 1.4.0 supports psr/log 1.0|2.0|3.0
The master is also compatible but reserved to the next release 2.0

Best regards

**Comment by VGirol** [comment]
Great !
Thank you very much.
